# Generated by Django 6.0.5 on 2026-05-13 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('name', models.CharField(choices=[('welcome', 'Welcome'), ('kyc', 'KYC'), ('transaction', 'Transaction'), ('refund', 'Refund')], max_length=100, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='emails_emai_name_dfce91_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=210)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient'], name='emails_emai_recipie_afcff3_idx'), models.Index(fields=['status'], name='emails_emai_status_445744_idx'), models.Index(fields=['sent_at'], name='emails_emai_sent_at_d5df86_idx')],
            },
        ),
    ]
