# Generated by Django 6.0.5 on 2026-05-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('kyc', 'KYC'), ('transaction_completed', 'Transaction Completed'), ('refund', 'Refund')], max_length=100, unique=True),
        ),
    ]
