# Generated by Django 6.0.5 on 2026-05-10 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('from_wallet_id', models.UUIDField()),
                ('to_wallet_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('pkr', 'PKR'), ('usd', 'USD'), ('eur', 'EUR'), ('gbp', 'GBP')], default='pkr', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('validating', 'Validating'), ('processing', 'Processing'), ('clearing', 'Clearing'), ('settled', 'Settled'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('transaction_type', models.CharField(choices=[('p2p', 'P2P'), ('merchant', 'Merchant'), ('bill', 'Bill'), ('remittance', 'Remittance'), ('refund', 'Refund')], max_length=20)),
                ('idempotency_key', models.CharField(max_length=270, unique=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['idempotency_key'], name='transaction_idempot_68455c_idx'), models.Index(fields=['from_wallet_id'], name='transaction_from_wa_8257c5_idx'), models.Index(fields=['to_wallet_id'], name='transaction_to_wall_b17f16_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx'), models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('percentage_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(choices=[('pkr', 'PKR'), ('usd', 'USD'), ('eur', 'EUR'), ('gbp', 'GBP')], default='pkr', max_length=3)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=270, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=270, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=270, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
