# Generated by Django 6.0.5 on 2026-05-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
