# Generated by Django 6.0.5 on 2026-05-11 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventProjection',
            fields=[
                ('aggregate_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('aggregate_type', models.CharField(max_length=30)),
                ('current_state', models.JSONField(default=dict)),
                ('last_event_id', models.UUIDField()),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RecordEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('aggregate_type', models.CharField(max_length=30)),
                ('payload', models.JSONField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['aggregate_id', 'created_at'], name='events_reco_aggrega_af6619_idx')],
            },
        ),
    ]
