# Generated by Django 6.0.5 on 2026-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recordevent',
            index=models.Index(fields=['event_type', 'created_at'], name='events_reco_event_t_fc561d_idx'),
        ),
    ]
