# Generated by Django 6.0.5 on 2026-05-11 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('original_transaction_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=25)),
                ('requested_by', models.UUIDField()),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('refund_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_origin', to='transactions.transaction')),
            ],
            options={
                'indexes': [models.Index(fields=['original_transaction_id'], name='refunds_ref_origina_d4b655_idx'), models.Index(fields=['status'], name='refunds_ref_status_4bb841_idx'), models.Index(fields=['requested_by'], name='refunds_ref_request_6d4136_idx')],
            },
        ),
    ]
