# Generated by Django 6.0.5 on 2026-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_transaction',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
