# Generated by Django 6.0.5 on 2026-05-08 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('currency', models.CharField(choices=[('pkr', 'PKR'), ('usd', 'USD'), ('gbp', 'GBP'), ('aed', 'AED')], default='pkr', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('suspended', 'Suspended')], default='active', max_length=15)),
            ],
            options={
                'indexes': [models.Index(fields=['currency', 'user_id'], name='wallets_wal_currenc_09d754_idx')],
                'unique_together': {('user_id', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='WalletBookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('reason', models.CharField(max_length=270)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_released', models.BooleanField(default=False)),
                ('is_committed', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='wallets.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('tier', models.CharField(choices=[('tier1', 'Tier1'), ('tier2', 'Tier2'), ('tier3', 'Tier3')], default='tier1')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=20000.0, max_digits=30)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=5000000.0, max_digits=30)),
                ('transaction_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=30)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to='wallets.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
