# Generated by Django 6.0.5 on 2026-05-08 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=12)),
                ('description', models.CharField(max_length=270)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record', to='wallets.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
