# Generated by Django 6.0.5 on 2026-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_walletrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletlimit',
            name='daily_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
