# Generated by Django 6.0.5 on 2026-05-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_walletlimit_daily_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='available_balance',
        ),
    ]
