# Generated by Django 6.0.5 on 2026-05-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_remove_wallet_available_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletlimit',
            name='daily_spent',
        ),
    ]
