# Generated by Django 6.0.5 on 2026-05-07 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=25)),
                ('tier', models.CharField(choices=[('tier1', 'Tier1'), ('tier2', 'Tier2'), ('tier3', 'Tier3')], default='tier1', max_length=25)),
                ('cnic_front_image', models.ImageField(blank=True, null=True, upload_to='kyc/cnic/')),
                ('cnic_back_image', models.ImageField(blank=True, null=True, upload_to='kyc/cnic/')),
                ('utility_bill_image', models.ImageField(blank=True, null=True, upload_to='kyc/bills/')),
                ('biometric_hash', models.CharField(blank=True, max_length=270, null=True)),
                ('is_biometric_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rej_reason', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('method', models.CharField(choices=[('cnic', 'CNIC'), ('biometric', 'Biometric'), ('manual', 'Manual'), ('nadra', 'NADRA')], max_length=30)),
                ('status', models.CharField(max_length=55)),
                ('metadata', models.JSONField(default=dict)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='kyc.kycprofile')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['status', 'is_verified'], name='kyc_kycprof_status_f65af2_idx'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['user', 'is_verified'], name='kyc_kycprof_user_id_972cce_idx'),
        ),
    ]
