# Generated by Django 6.0.5 on 2026-05-09 19:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0005_remove_walletlimit_daily_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('reason', models.CharField(choices=[('rapid', 'Rapid'), ('large', 'Large'), ('unusual', 'Unusual')], max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='transaction details context.')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.UUIDField(blank=True, help_text='admin user id', null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='wallets.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailySpending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=40)),
                ('transaction_count', models.IntegerField(default=0)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spendings', to='wallets.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'date'], name='limits_dail_wallet__16edcb_idx')],
                'unique_together': {('wallet', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySpending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=40)),
                ('transaction_count', models.IntegerField(default=0)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_spendings', to='wallets.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet', 'year', 'month'], name='limits_mont_wallet__8a3ff9_idx')],
                'unique_together': {('wallet', 'year', 'month')},
            },
        ),
    ]
