# Generated by Django 6.0.5 on 2026-05-13 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('bank_name', models.CharField(choices=[('hbl', 'HBL'), ('ubl', 'UBL'), ('mcb', 'MCB'), ('allied', 'Allied'), ('fb', 'FB')], max_length=110)),
                ('account_number', models.CharField(max_length=60)),
                ('statement_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=22)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=22)),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=30)),
            ],
            options={
                'ordering': ['-statement_date'],
                'indexes': [models.Index(fields=['bank_name', 'account_number'], name='statements__bank_na_bbd2db_idx'), models.Index(fields=['statement_date'], name='statements__stateme_8783ac_idx'), models.Index(fields=['status'], name='statements__status_a7566b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=110, null=True)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=14)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='statements.bankstatement')),
            ],
            options={
                'ordering': ['transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='SettlementDifference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('internal_transaction_id', models.UUIDField(blank=True, null=True)),
                ('difference_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('reason', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differences', to='statements.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('internal_transaction_id', models.UUIDField()),
                ('match_confidence', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('disputed', 'Disputed')], default='matched', max_length=30)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='statements.banktransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['statement', 'transaction_date'], name='statements__stateme_328f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reference_number'], name='statements__referen_43143b_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['amount'], name='statements__amount_1cad75_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementdifference',
            index=models.Index(fields=['is_resolved'], name='statements__is_reso_f11b67_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementdifference',
            index=models.Index(fields=['internal_transaction_id'], name='statements__interna_b5ad35_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementmatch',
            index=models.Index(fields=['internal_transaction_id'], name='statements__interna_19b5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementmatch',
            index=models.Index(fields=['status'], name='statements__status_ca15d8_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementmatch',
            index=models.Index(fields=['match_confidence'], name='statements__match_c_2954e9_idx'),
        ),
    ]
