# Generated by Django 6.0.5 on 2026-05-12 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('base_currency', models.CharField(choices=[('pkr', 'PKR'), ('usd', 'USD'), ('gbp', 'GBP'), ('eur', 'EUR'), ('aed', 'AED'), ('cad', 'CAD'), ('aud', 'AUD')], max_length=5)),
                ('quote_currency', models.CharField(choices=[('pkr', 'PKR'), ('usd', 'USD'), ('gbp', 'GBP'), ('eur', 'EUR'), ('aed', 'AED'), ('cad', 'CAD'), ('aud', 'AUD')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'quote_currency'], name='rates_curre_base_cu_a69a97_idx'), models.Index(fields=['is_active'], name='rates_curre_is_acti_0631fe_idx')],
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(blank=True, max_length=110, null=True)),
                ('from_currency', models.CharField(max_length=4)),
                ('to_currency', models.CharField(max_length=4)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('host', 'Host'), ('open', 'Open'), ('sbp', 'SBP')], default='manual', max_length=50)),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'effective_from'], name='rates_excha_from_cu_51e7ba_idx'), models.Index(fields=['effective_from'], name='rates_excha_effecti_7c91c8_idx'), models.Index(fields=['source'], name='rates_excha_source_63509e_idx')],
                'unique_together': {('from_currency', 'to_currency', 'effective_from')},
            },
        ),
    ]
